# Form implementation generated from reading ui file 'ui_error_window.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 150)
        Dialog.setMinimumSize(QtCore.QSize(300, 150))
        Dialog.setMaximumSize(QtCore.QSize(300, 150))
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(0, 40, 300, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.ok_pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.ok_pushButton.setGeometry(QtCore.QRect(110, 90, 80, 50))
        self.ok_pushButton.setMaximumSize(QtCore.QSize(80, 50))
        self.ok_pushButton.setStyleSheet("")
        self.ok_pushButton.setObjectName("ok_pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Ошибка"))
        self.label.setText(_translate("Dialog", "Необходимо выделить один id"))
        self.ok_pushButton.setText(_translate("Dialog", "OK"))
